### ISSUE TITLE
Error when fitting mogsa function on miniACC dataset

### ISSUE THREAD

**Issue by ryf0810** [mengchen18/mogsa#2]
Dear author,

In this chunk of code, I tried to create the support data for mutation matrix, which is from MultiAssayExperiment package. But when I fit mogsa function, it showed an error that 'object r not found', I have met this error a lot of time, and I have no clue about how to solve this. May I ask any help from you to give me some hints? Thank you so much!

mutation <- assay(miniACC[[4]])

keggdb <- prepGraphite(db = pathways("hsapiens", "kegg")[1:50], id = "symbol")
keggdb <- lapply(keggdb, function(x) sub("SYMBOL:", "", x))

supp <- prepSupMoa(mutation, geneSets=keggdb, minMatch=1)

mgsa1 <- mogsa(x=mutation, sup=supp, nf=3, proc.row = "center_ssq1", w.data = "inertia", statis = TRUE)

Error in new("mgsa", call = match.call(), moa = r, sup = supr) : 
object 'r' not found

**Comment by mengchen18** [comment]
Hi, Thanks for reporting this. That because the argument of "x" in mogsa function expects a list of matrices or an "moa" object. In your case, the "mutation" is a matrix/array. 
I will make an update to make this more clear.
